
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mokleters
 */
public class Pemesanan extends javax.swing.JFrame {

    
    public Pemesanan() {
        initComponents();
        SetWaktu();
        SetTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        wkt = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        HargaItem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jumlahItem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nItem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nStruk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData1 = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        print = new javax.swing.JButton();
        totalhrg = new javax.swing.JButton();
        hrgTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("PRIMETIME", 1, 36)); // NOI18N
        jLabel1.setText("Resto Ala-Ala");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 0, 380, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Semua Adaaa");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 40, 180, 20);

        wkt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wkt.setText("Waktu");
        jPanel2.add(wkt);
        wkt.setBounds(590, 50, 100, 20);

        tgl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tgl.setText("Tanggal");
        jPanel2.add(tgl);
        tgl.setBounds(590, 30, 100, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nama Kasir : Joice Jessica");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(590, 10, 180, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, -1, 1040, 70);

        clear.setBackground(new java.awt.Color(0, 0, 0));
        clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(150, 320, 90, 30);

        Save.setBackground(new java.awt.Color(0, 0, 0));
        Save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save);
        Save.setBounds(30, 320, 90, 30);

        HargaItem.setFont(new java.awt.Font("MS Mincho", 0, 12)); // NOI18N
        HargaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaItemActionPerformed(evt);
            }
        });
        jPanel1.add(HargaItem);
        HargaItem.setBounds(30, 280, 210, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Harga");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 260, 120, 20);

        jumlahItem.setFont(new java.awt.Font("MS Mincho", 0, 12)); // NOI18N
        jumlahItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahItemActionPerformed(evt);
            }
        });
        jPanel1.add(jumlahItem);
        jumlahItem.setBounds(30, 220, 210, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Jumlah ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 200, 120, 20);

        nItem.setFont(new java.awt.Font("MS Mincho", 0, 12)); // NOI18N
        nItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nItemActionPerformed(evt);
            }
        });
        jPanel1.add(nItem);
        nItem.setBounds(30, 160, 210, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nama Makanan/Minuman");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 140, 230, 20);

        nStruk.setFont(new java.awt.Font("MS Mincho", 0, 12)); // NOI18N
        nStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nStrukActionPerformed(evt);
            }
        });
        jPanel1.add(nStruk);
        nStruk.setBounds(30, 100, 210, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("No. Struk");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 80, 80, 20);

        tableData1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Struk", "Nama Item", "JumlahItem", "HargaItem"
            }
        ));
        jScrollPane1.setViewportView(tableData1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(310, 100, 452, 150);

        delete.setBackground(new java.awt.Color(0, 0, 0));
        delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(310, 260, 80, 30);

        refresh.setBackground(new java.awt.Color(0, 0, 0));
        refresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refresh.setForeground(new java.awt.Color(255, 255, 255));
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh);
        refresh.setBounds(420, 260, 90, 30);

        print.setBackground(new java.awt.Color(0, 0, 0));
        print.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print);
        print.setBounds(540, 260, 80, 30);

        totalhrg.setBackground(new java.awt.Color(0, 0, 0));
        totalhrg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalhrg.setForeground(new java.awt.Color(255, 255, 255));
        totalhrg.setText("Total");
        totalhrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalhrgActionPerformed(evt);
            }
        });
        jPanel1.add(totalhrg);
        totalhrg.setBounds(640, 260, 80, 30);

        hrgTotal.setFont(new java.awt.Font("MS Mincho", 0, 14)); // NOI18N
        jPanel1.add(hrgTotal);
        hrgTotal.setBounds(420, 300, 150, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Total Harga");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(310, 310, 100, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 780);

        setBounds(0, 0, 804, 422);
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        nStruk.setText("");
        nItem.setText("");
        jumlahItem.setText("");
        HargaItem.setText("");
        HargaItem.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        if ("".equals(nItem.getText()) || "".equals(jumlahItem.getText()) || "".equals(HargaItem.getText()))
        {
            JOptionPane.showMessageDialog(this, "Data harus diisi","Error", JOptionPane.WARNING_MESSAGE);

        }else{
            int harga = Integer.parseInt(String.valueOf(HargaItem.getText()));
            int jml = Integer.parseInt(String.valueOf(jumlahItem.getText()));
            int total = harga*jml;

            HargaItem.setText(String.valueOf(total));

        }

        //        int struk = 1;

        String SQL = "INSERT INTO tb_menu(no_struk,nama_item,jumlah_item,harga_item)"+
        "VALUES('"+nStruk.getText()+"','"+nItem.getText()+"','"+jumlahItem.getText()+"','"+HargaItem.getText()+"')";
        int status = KoneksiDB.execute(SQL);
        if (status==1) {
            JOptionPane.showMessageDialog(this,"Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
            selectdata();
        }
        else{
            JOptionPane.showMessageDialog(this,"Data gagal ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void HargaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaItemActionPerformed

    private void jumlahItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahItemActionPerformed

    private void nItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nItemActionPerformed

    private void nStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nStrukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nStrukActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Anda yakin Menghapus Data!","",JOptionPane.YES_NO_OPTION);
        int baris = tableData1.getSelectedRow();
        if (konfirmasi ==0) {

            if (baris != -1) {
                String id = tableData1.getValueAt(baris, 0).toString();
                String SQL = "DELETE FROM tb_menu WHERE no_struk='"+nStruk.getText()+"'";
                int status = KoneksiDB.execute(SQL);

                if (status==1) {
                    JOptionPane.showMessageDialog(this,"Data Berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                }else {
                    JOptionPane.showMessageDialog(this,"Data Gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this,"Pilih Baris Data Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        selectdata();
        
    }//GEN-LAST:event_refreshActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        MessageFormat header = new MessageFormat ("Daftar Transaksi Patria Stationary");
        MessageFormat footer = new MessageFormat ("Page {0, number, integer}");
        try{
            tableData1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("Cannot Prnt %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    private void totalhrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalhrgActionPerformed
        int jmlBaris = tableData1.getRowCount();
        int totalBiaya = 0;
        int jmlBarang, hargaBarang;
        TableModel tabelModel;
        tabelModel = tableData1.getModel();
        for (int i=0; i<jmlBaris; i++){
            jmlBarang = Integer.parseInt(tabelModel.getValueAt(i, 2).toString());
            hargaBarang = Integer.parseInt(tabelModel.getValueAt(i, 3).toString());
            totalBiaya = totalBiaya + (jmlBarang*hargaBarang);
        }
        if (totalBiaya > 200000) {
            int diskon = totalBiaya*10/100;
            hrgTotal.setText(String.valueOf(totalBiaya-diskon));
        }else
        hrgTotal.setText(String.valueOf(totalBiaya));
    }//GEN-LAST:event_totalhrgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HargaItem;
    private javax.swing.JButton Save;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField hrgTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahItem;
    private javax.swing.JTextField nItem;
    private javax.swing.JTextField nStruk;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JTable tableData1;
    private javax.swing.JLabel tgl;
    private javax.swing.JButton totalhrg;
    private javax.swing.JLabel wkt;
    // End of variables declaration//GEN-END:variables

    private void selectdata() 
    {
        String kolom[]={"No. Struk","Nama Item","JumlahItem","HargaItem"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);   
        String SQL = "SELECT * FROM tb_menu";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String id = rs.getString(1);
                String item = rs.getString(2);
                String jumlah = rs.getString(3);
                String harga = rs.getString(4);
//                String total = rs.getString(5);
                    String data[] = {id,item,jumlah,harga};
                    dtm.addRow(data);
            }
        }   catch(SQLException ex){
                    Logger.getLogger(Pemesanan.class.getName()).log(Level.SEVERE,null, ex);
                    }
            tableData1.setModel(dtm);
    }

    private void SetWaktu() {
        ActionListener taskPerformer = new ActionListener(){
        public void actionPerformed(ActionEvent evt){
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                
                
                Date dt = new Date();
                int vh = dt.getHours();
                int vm = dt.getMinutes();
                int vs = dt.getSeconds();
                
                if (vh<=9){
                    nol_jam = "0";
                } if (vm <= 9) {
                    nol_menit = "0";
                } if (vs <= 9){
                    nol_detik = "0";
                }
               
                
                String h = nol_jam + Integer.toString(vh);
                String m = nol_menit + Integer.toString(vm);
                String s = nol_detik + Integer.toString(vs);
                wkt.setText(h+":"+m+":"+s);
            }
    };

   new Timer(100, taskPerformer).start();
    }

    private void SetTanggal() {
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyy/MM/dd");
        tgl.setText(kal.format(now));    
    }
}
